// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SmartBike.Migrations
{
    [DbContext(typeof(SmartBikeContext))]
    partial class SmartBikeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modelos.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampusId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("CampusId");

                    b.ToTable("campus");
                });

            modelBuilder.Entity("Modelos.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarreraId"));

                    b.Property<int>("FacultadId")
                        .HasColumnType("integer")
                        .HasColumnName("facultad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("CarreraId");

                    b.HasIndex("FacultadId");

                    b.ToTable("carreras");
                });

            modelBuilder.Entity("Modelos.ConversacionChatbot", b =>
                {
                    b.Property<int>("ConversacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("conversacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversacionId"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("UsuarioCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("usuario_cedula");

                    b.HasKey("ConversacionId");

                    b.HasIndex("UsuarioCedula");

                    b.ToTable("conversaciones_chatbot");
                });

            modelBuilder.Entity("Modelos.Estacionamiento", b =>
                {
                    b.Property<string>("EstacionamientoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estacionamiento_id");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<int>("EstadoEstacionamientoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_estacionamiento_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("EstacionamientoId");

                    b.HasIndex("CampusId");

                    b.HasIndex("EstadoEstacionamientoId");

                    b.ToTable("estacionamientos");
                });

            modelBuilder.Entity("Modelos.EstadoEstacionamiento", b =>
                {
                    b.Property<int>("EstadoEstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("estado_estacionamiento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstadoEstacionamientoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nombre");

                    b.HasKey("EstadoEstacionamientoId");

                    b.ToTable("estados_estacionamiento");
                });

            modelBuilder.Entity("Modelos.Facultad", b =>
                {
                    b.Property<int>("FacultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("facultad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacultadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("FacultadId");

                    b.ToTable("facultades");
                });

            modelBuilder.Entity("Modelos.InteraccionChatbot", b =>
                {
                    b.Property<int>("InteraccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interaccion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InteraccionId"));

                    b.Property<int>("ConversacionId")
                        .HasColumnType("integer")
                        .HasColumnName("conversacion_id");

                    b.Property<DateTime>("FechaInteraccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_interaccion");

                    b.Property<string>("MensajeUsuario")
                        .HasColumnType("text")
                        .HasColumnName("mensaje_usuario");

                    b.Property<int?>("PreguntaId")
                        .HasColumnType("integer")
                        .HasColumnName("pregunta_id");

                    b.Property<string>("RespuestaBot")
                        .HasColumnType("text")
                        .HasColumnName("respuesta_bot");

                    b.HasKey("InteraccionId");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("interacciones_chatbot");
                });

            modelBuilder.Entity("Modelos.MetricaUsuario", b =>
                {
                    b.Property<string>("UsuarioCedula")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("usuario_cedula");

                    b.Property<int>("DiasRegistrados")
                        .HasColumnType("integer")
                        .HasColumnName("dias_registrados");

                    b.Property<int>("MejorRachaDias")
                        .HasColumnType("integer")
                        .HasColumnName("mejor_racha_dias");

                    b.Property<int>("RachaActualDias")
                        .HasColumnType("integer")
                        .HasColumnName("racha_actual_dias");

                    b.Property<decimal>("TotalAhorroDolares")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_ahorro_dolares");

                    b.Property<decimal>("TotalCalorias")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_calorias");

                    b.Property<decimal>("TotalCo2EvitadoG")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_co2_evitado_g");

                    b.Property<decimal>("TotalKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_km");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("UsuarioCedula");

                    b.ToTable("metricas_usuario");
                });

            modelBuilder.Entity("Modelos.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permiso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("CodigoPermiso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_permiso");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.HasKey("PermisoId");

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("Modelos.PreguntaFrecuente", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pregunta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PreguntaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("RespuestaDefault")
                        .HasColumnType("text")
                        .HasColumnName("respuesta_default");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("texto_pregunta");

                    b.HasKey("PreguntaId");

                    b.ToTable("preguntas_frecuentes");
                });

            modelBuilder.Entity("Modelos.RegistroViaje", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroId"));

                    b.Property<decimal>("DistanciaKm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("distancia_km");

                    b.Property<string>("EstacionamientoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estacionamiento_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("TipoTransporteId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_transporte_id");

                    b.Property<string>("UsuarioCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("usuario_cedula");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean")
                        .HasColumnName("validado");

                    b.Property<string>("ValidadoPor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("validado_por");

                    b.HasKey("RegistroId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoTransporteId");

                    b.ToTable("registros_viajes");
                });

            modelBuilder.Entity("Modelos.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("RolId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Modelos.TipoTransporte", b =>
                {
                    b.Property<int>("TipoTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_transporte_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoTransporteId"));

                    b.Property<decimal>("FactorAhorroDolarKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("factor_ahorro_dolar_km");

                    b.Property<decimal>("FactorCaloriasKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("factor_calorias_km");

                    b.Property<decimal>("FactorCo2GKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("factor_co2_g_km");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoTransporteId");

                    b.ToTable("tipos_transporte");
                });

            modelBuilder.Entity("Modelos.Usuario", b =>
                {
                    b.Property<string>("Cedula")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cedula");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellidos");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int?>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correo_institucional");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombres");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("Cedula");

                    b.HasIndex("CampusId");

                    b.HasIndex("CarreraId");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("PermisosPermisoId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesRolId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosPermisoId", "RolesRolId");

                    b.HasIndex("RolesRolId");

                    b.ToTable("PermisoRol");
                });

            modelBuilder.Entity("Modelos.Carrera", b =>
                {
                    b.HasOne("Modelos.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("Modelos.ConversacionChatbot", b =>
                {
                    b.HasOne("Modelos.Usuario", "Usuario")
                        .WithMany("Conversaciones")
                        .HasForeignKey("UsuarioCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Modelos.Estacionamiento", b =>
                {
                    b.HasOne("Modelos.Campus", "Campus")
                        .WithMany("Estacionamientos")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.EstadoEstacionamiento", "Estado")
                        .WithMany("Estacionamientos")
                        .HasForeignKey("EstadoEstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Modelos.InteraccionChatbot", b =>
                {
                    b.HasOne("Modelos.ConversacionChatbot", "Conversacion")
                        .WithMany("Interacciones")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.PreguntaFrecuente", "PreguntaFrecuente")
                        .WithMany("Interacciones")
                        .HasForeignKey("PreguntaId");

                    b.Navigation("Conversacion");

                    b.Navigation("PreguntaFrecuente");
                });

            modelBuilder.Entity("Modelos.MetricaUsuario", b =>
                {
                    b.HasOne("Modelos.Usuario", "Usuario")
                        .WithOne("Metricas")
                        .HasForeignKey("Modelos.MetricaUsuario", "UsuarioCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Modelos.RegistroViaje", b =>
                {
                    b.HasOne("Modelos.Estacionamiento", null)
                        .WithMany("RegistrosViajes")
                        .HasForeignKey("EstacionamientoId");

                    b.HasOne("Modelos.TipoTransporte", null)
                        .WithMany("RegistrosViajes")
                        .HasForeignKey("TipoTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelos.Usuario", b =>
                {
                    b.HasOne("Modelos.Campus", "Campus")
                        .WithMany("Usuarios")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Carrera", "Carrera")
                        .WithMany("Usuarios")
                        .HasForeignKey("CarreraId");

                    b.HasOne("Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Carrera");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("Modelos.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelos.Campus", b =>
                {
                    b.Navigation("Estacionamientos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelos.Carrera", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelos.ConversacionChatbot", b =>
                {
                    b.Navigation("Interacciones");
                });

            modelBuilder.Entity("Modelos.Estacionamiento", b =>
                {
                    b.Navigation("RegistrosViajes");
                });

            modelBuilder.Entity("Modelos.EstadoEstacionamiento", b =>
                {
                    b.Navigation("Estacionamientos");
                });

            modelBuilder.Entity("Modelos.Facultad", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("Modelos.PreguntaFrecuente", b =>
                {
                    b.Navigation("Interacciones");
                });

            modelBuilder.Entity("Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelos.TipoTransporte", b =>
                {
                    b.Navigation("RegistrosViajes");
                });

            modelBuilder.Entity("Modelos.Usuario", b =>
                {
                    b.Navigation("Conversaciones");

                    b.Navigation("Metricas");
                });
#pragma warning restore 612, 618
        }
    }
}
